"""Pydantic schemas for request/response validation."""

from app.schemas.auth import Token, TokenPayload
from app.schemas.user import UserCreate, UserRead, UserUpdate
from app.schemas.weather import (
    WeatherDataOut,
    WeatherModelsOut,
    WeatherRecordOut,
    WeatherResolutionsOut,
)
from app.schemas.wind_energy import (
    GenerationRecordBulkCreate,
    GenerationRecordCreate,
    GenerationRecordRead,
    LocationCreate,
    LocationRead,
    LocationUpdate,
    PowerCurveCreate,
    PowerCurveRead,
    PowerCurveUpdate,
    WindFarmCreate,
    WindFarmGenerationRecordBulkCreate,
    WindFarmGenerationRecordCreate,
    WindFarmGenerationRecordRead,
    WindFarmRead,
    WindFarmUpdate,
    WindRecordBulkCreate,
    WindRecordCreate,
    WindRecordRead,
    WindTurbineCreate,
    WindTurbineFleetCreate,
    WindTurbineFleetRead,
    WindTurbineFleetUpdate,
    WindTurbineRead,
    WindTurbineUpdate,
)

__all__ = [
    "Token",
    "TokenPayload",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "LocationCreate",
    "LocationRead",
    "LocationUpdate",
    "PowerCurveCreate",
    "PowerCurveRead",
    "PowerCurveUpdate",
    "WindTurbineCreate",
    "WindTurbineRead",
    "WindTurbineUpdate",
    "WindFarmCreate",
    "WindFarmRead",
    "WindFarmUpdate",
    "WindTurbineFleetCreate",
    "WindTurbineFleetRead",
    "WindTurbineFleetUpdate",
    "WindRecordCreate",
    "WindRecordRead",
    "WindRecordBulkCreate",
    "GenerationRecordCreate",
    "GenerationRecordRead",
    "GenerationRecordBulkCreate",
    "WindFarmGenerationRecordCreate",
    "WindFarmGenerationRecordRead",
    "WindFarmGenerationRecordBulkCreate",
    "WeatherRecordOut",
    "WeatherDataOut",
    "WeatherModelsOut",
    "WeatherResolutionsOut",
]
