"""add_wind_energy_models

Revision ID: 923bd7bcc78e
Revises: 4509efc461a3
Create Date: 2026-01-01 14:44:37.060192

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "923bd7bcc78e"
down_revision: str | None = "4509efc461a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "powercurve",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("wind_speed_value_map", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "windfarm",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "windrecord",
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("wind_direction", sa.Float(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "windturbine",
        sa.Column("turbine_type", sa.String(length=255), nullable=True),
        sa.Column("hub_height", sa.Float(), nullable=False),
        sa.Column("nominal_power", sa.Float(), nullable=False),
        sa.Column("power_curve_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["power_curve_id"],
            ["powercurve.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "windturbinefleet",
        sa.Column("wind_farm_id", sa.Integer(), nullable=False),
        sa.Column("wind_turbine_id", sa.Integer(), nullable=False),
        sa.Column("number_of_turbines", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wind_farm_id"],
            ["windfarm.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wind_turbine_id"],
            ["windturbine.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "windturbinegenerationrecord",
        sa.Column("wind_turbine_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generation", sa.Float(), nullable=False),
        sa.Column(
            "granularity",
            sa.Enum(
                "min_1", "min_5", "min_15", "min_30", "min_60", name="granularityenum"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wind_turbine_id"],
            ["windturbine.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("windturbinegenerationrecord")
    op.drop_table("windturbinefleet")
    op.drop_table("windturbine")
    op.drop_table("windrecord")
    op.drop_table("windfarm")
    op.drop_table("powercurve")
    op.drop_table("location")
    # ### end Alembic commands ###
